[[custom_command]]
label = "Echo Message"
url_endpoint = "echo-message"
run_cmd = ["echo", "Hello, world!"]
stdin_allow = false
enabled = true

[[custom_command]]
label = "Echo another message"
url_endpoint = "echo-message2"
run_cmd = ["echo", "Hey there!"]
stdin_allow = false
enabled = false

[[custom_command]]
label = "Combine with stdin"
url_endpoint = "echo-message2"
run_cmd = ["sed", "'s/$/ World!/'"]
stdin_allow = true
stdin_placeholder_text = "What else to echo?"
stdin_is_password = false
enabled = true

[[custom_command]]
label = "One more echo"
url_endpoint = "echo-message3"
run_cmd = ["echo", "Not happening!"]
stdin_allow = false
stdin_placeholder_text = ""
enabled = false
