[package]
name = "common"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "1.0"

# Note that you can't use "full" feature here, because unix sockets don't compile in wasm
tokio = { version = "1.39", features = ["rt", "time"] }
