# Live configuration
# [mode.live]
# base_url = "https://example.com"

# Mock configuration
[mode.mock]
# Simualted datasets
datasets_and_passwords = [
    # Dataset name, key password, probability of failing
    ["dataset1", "password1", 0.0],
    ["dataset2", "password2", 0.0],
    ["dataset3", "password3", 0.1],
    ["dataset4", "password4", 0.1]
]
