# Live configuration
# [mode.live]
# base_url = "http://192.168.1.78:6677"

# Mock configuration
[mode.mock]
# Simualted datasets
datasets_and_passwords = [
    # Dataset name, key password, probability of failing
    ["dataset1", "password1", 0.0],
    ["dataset2", "password2", 0.0],
    ["dataset3", "password3", 0.1],
    ["dataset4", "password4", 0.1],
    ["dataset5", "password5", 0.1]
]

commands = [
    ["Echo hello", "Hello world!", "Hello error!", 0, true],
    ["Echo another", "Hello another world!", "Hello another error!", 1, false],
    ["Echo even another", "Hello even another world!", "Hello even another error!", 5, false]
]
